### ISSUE TITLE
Add right click on white space

### ISSUE THREAD

**Issue by themedleb** [nextcloud/files_rightclick#103]
I would love to have right-click on the white space (where the files are) that acts like the plus button on the top to upload a file and  add new folder, text, document spreadsheet, presentation, ...

**Comment by briantho** [comment]
I totally agree, If you right click inside a blank folder, or below a file, or in your words "white space" a right click menu should pop up asking to create a text document, new folder, etc. Can this be added. This feature really should be implemented.
