### ISSUE TITLE
nextcloud 19

### ISSUE THREAD

**Issue by xlangyun** [nextcloud/files_rightclick#104]
Is there a version  working with nextcloud 19?
What can I to do about it?

**Comment by krayzie0x10** [comment]
Bump!
My Users/Customers likes this!

**Comment by sunjam** [comment]
I was able to install on Nextcloud 20; working fine so far.  Just _enable untested_, then _enable_.

**Comment by Thulium-Drake** [comment]
You also might need to edit info.xml and set max supported release of Nextcloud to 21 (or 30 to postpone any errors for a while)
