### ISSUE TITLE
Ability to upload a new file version while preserving the online filename

### ISSUE THREAD

**Issue by nekohayo** [nextcloud/files_rightclick#108]
I often name files differently online than I name them on my local filesystem. I would like to be able to upload new versions of those files seamlessly, by right-clicking (or from the "Versions" tab of the file details sidebar) and choosing to "Upload a new version of this file", so that whatever file I upload as a replacement gets named the same way as it is named online, regardless of the name of the local file on my computer. Google Drive allows this, and it is very convenient.

**Comment by Wirrus** [comment]
This would be really helpful

**Comment by apolat** [comment]
That was also what I was looking for. I hope to see it in the eariest.
