### ISSUE TITLE
右键点击菜单上面没有“共享”这个选项

### ISSUE THREAD

**Issue by lqianglu** [nextcloud/files_rightclick#114]
![image](https://user-images.githubusercontent.com/79095178/110125880-c67a4880-7dfe-11eb-87a5-42b3a9cdf890.png)
nextcloud版本21，已删除自带的右键点击

**Comment by NastuzziSamy** [comment]
Hi @lqianglu, thank you for your issue. 

Can you explain it in english pls ?

**Comment by NastuzziSamy** [comment]
No information given, closing
