### ISSUE TITLE
Delete only works somethimes in NC 23

### ISSUE THREAD

**Issue by harmoniemand** [nextcloud/files_rightclick#125]
It seems like right click on a file to delete does not work most of the time in NC 23 while working with the three dots works fine every time. Does anyone else got this error?

**Comment by leon-erd** [comment]
Yes same for me! Actually now the right click menu isn't working at all.
I noticed that I could only rename a file/folder sometimes (I guess it was the same for "delete") after the update to NC 23. Now when I click on anything in the right click menu nothing happens. Everything works when marking the file/folder and clicking on the three dots ("Actions") as described by the OP.

**Comment by matcho** [comment]
Using Firefox under Linux, same problem: menu appears but clicking any of its items barely works half the time. Works fine when using Chrome, though.
