### ISSUE TITLE
Right click does not work

### ISSUE THREAD

**Issue by Xerionty** [nextcloud/files_rightclick#14]
The addon does not work at all on a clean Nextcloud 12 version (0.6.0).
I have reinstalled the addon without succes. No errors are logged.

 On my version 13 it's working flawless.

**Comment by NastuzziSamy** [comment]
Ok thanks for the feedback.

The application is no more NC 12 friendly (https://github.com/NastuzziSamy/files_rightclick/commit/87b577a2436679420b5f10ade96cc7e89b685499), until I find a solution.

**Comment by Xerionty** [comment]
Unfortunate, but thanks for the reply. Makes sense now.

**Comment by zorn-v** [comment]
What problem with NC12, maybe I can help ?

**Comment by zorn-v** [comment]
If you put `console.log(delimiter);` here https://github.com/NastuzziSamy/files_rightclick/blob/master/js/script.js#L178 in NC12 `length` will be `0`, but in NC13 it will be `3`
Seems your script runs early than needed in NC12 (when no `tbody[id=fileList]` yet on page)
Maybe it helps.

**Comment by NastuzziSamy** [comment]
Ok thank you a lot @zorn

I will add a function which will check if the delimiter exists and check until it exists to apply the contextmenu

**Comment by zorn-v** [comment]
You can use jQuery `delegate` on some container (in which filelist) instead of "infinity" checks.

**Comment by alx-tuilmenau** [comment]
Got the same problem on NC12 using 0.6.1. Changed the js/script.js at the end to execute the registration later. Seems to work.

```
$( document ).ready(function() { // added
        $('<style class="rightClickStyle"></style>').appendTo('head');
        $('table[id*=filestable]').contextmenu(openContextOnRightClick);
}); //added
```

**Comment by NastuzziSamy** [comment]
I'll release an update on the end of the week 😉
