### ISSUE TITLE
[25.0.0 beta 6]: Context menu not working

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/files_rightclick#143]
In Nextcloud version 25.0.0 beta 6, the context menu does not appear when pressing the right mouse button.

App:
Right click 1.4.0
Firefox 104.0.2

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo
