### ISSUE TITLE
edit locally in file app context menu not always present

### ISSUE THREAD

**Issue by rriemann** [nextcloud/files_rightclick#147]
I have today updated nextcloud to the latest version in beta channel. I run 25.0.0 RC3.

I noticed that the context menu has not always the entr "edit locally". It depends how you open it.

## Right click on file name does not have it:

![Screenshot_20221007_111117](https://user-images.githubusercontent.com/111932/194518391-1a225163-c152-4d30-9a13-f98cb7100adf.png)

## Click on 3-dot menu has it:

![image](https://user-images.githubusercontent.com/111932/194518551-4122e85a-3cc7-4254-8b1c-0186dd21ee22.png)

**Comment by PVince81** [comment]
I had a quick look at the code and I'm surprised that the right click menu isn't even accessing the FileActions data structure from the file list where actions are registered. This means that every time apps register new actions there, they will be missing in this menu.

**Comment by JojoBr0** [comment]
Is there an intention to update the right click menu to use the Standard File Action structure?
IMO the right click is a fundamental Feature.

**Comment by PVince81** [comment]
currently there are not plans to do so, at least not with the old jquery code in the file list

however there are plans to port the files app to Vue, so the right click app will also need to be adjusted to the modernized APIs
