### ISSUE TITLE
Menu "Move or copy" is not translated to different Languages

### ISSUE THREAD

**Issue by ZID-TU-Graz-Collab** [nextcloud/files_rightclick#176]
**Steps to reproduce**
1.	Choose a Language different than English (e.g. german or french)
2.	Go to files and right click or use the 3 dots on a file/folder
3.	Click on "Move or copy" in the dropdown menu (will have a different name due to language change in step 1)

**Expected behavior**

Menu and buttons shown in selected language.

**Actual Beahviour**

Only the title is translated.
Buttons and "Name", "Size", "Modified" in the files table are in english
tested with german and french. 

**Nextcloud Version:** 27.1.1

**Note:** No available translation in Transifex

Screenshot 1: Menu with german language in settings. name of the files covered with a grey box

![Menü bei deutscher Sprache](https://github.com/nextcloud/files_rightclick/assets/100593683/15be2fba-2138-4d09-9277-495c4f800a1a)

**Comment by ZID-TU-Graz** [comment]
Solved with Update to NC 27.1.5
