### ISSUE TITLE
Cannot Scroll or easily close menu

### ISSUE THREAD

**Issue by AurorahHarmony** [nextcloud/files_rightclick#51]
After right clicking, scrolling does not work within folders with many items. To close the menu, a click must be made somewhere on the screen, which often slows things down when trying not to click on a folder

**Comment by jancborchardt** [comment]
This actually is done the same way in Google Drive, as it ensures that the content or menu is not scrolled accidentally.

Technically, the scrollability of the list is suppressed while the menu is open (through overflow: hidden; on the file list container). If we don’t do that, the list would scroll while the menu would stay in place floating. That’s the bug we actually have for the share input suggestions dropdown.

So, we could make the scrolling possible _if_ there is a way to have the menu scroll the same way too.

Then again, the issue of not being able to close the menu quickly does not exist:

> To close the menu, a click must be made somewhere on the screen, which often slows things down when trying not to click on a folder

→ as you can actually click anywhere. Your first click won’t do anything, it will always only close the menu.
