### ISSUE TITLE
WebDAV link copy should close contextmenu

### ISSUE THREAD

**Issue by ShinjiLE** [nextcloud/files_rightclick#52]
After successfully copy the link , the menu should close itself.

**Comment by NastuzziSamy** [comment]
As we removed the option, the issue is no more relevant

**Comment by ShinjiLE** [comment]
Hi,
Why is this function removed ? It was usefull for me .

**Comment by EV21** [comment]
You can still copy a WebDAV-File-Link with the browser context-menu with "SHIFT + right-click" and just copy the link. 
Folders have different links, but you could just use the file-link and correct it by hand.

It was also news to me.
https://github.com/nextcloud/files_rightclick/issues/59
