### ISSUE TITLE
double menu-items share

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/files_rightclick#56]
Test with NC16.0.0 Beta 1
The 1st menu-item is "Share file" and the 2nd menu-item is "Share" too:

![Screenshot_2019-03-25 Documents - Files - Nextcloud(1)](https://user-images.githubusercontent.com/34692335/54937442-b2e0ba80-4f24-11e9-90bb-32249083a7d5.png)

Similar behavior with folders.

**Comment by NastuzziSamy** [comment]
Thx @cloud2018 , I had the same issue, I am working on it

**Comment by juliushaertl** [comment]
Seems to be fixed with beta2 :wink:

**Comment by cloud2018** [comment]
It seems, that with the fix the entries "comment" and "delete" are gone:
(delete ist still available in the 3-dots-menu)

![Screenshot_2019-03-29 Documents - Dateien - Nextcloud](https://user-images.githubusercontent.com/34692335/55224488-ecf5d900-5210-11e9-8914-27a1b99a1001.png)
