### ISSUE TITLE
Delete is missing from the right click menu

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/files_rightclick#57]
Regular menu:
![image](https://user-images.githubusercontent.com/3404133/55223618-e49c9e80-520e-11e9-939b-b6dee12fd8d4.png)

Right click menu:
![image](https://user-images.githubusercontent.com/3404133/55223629-ebc3ac80-520e-11e9-8a78-e783ad351934.png)

**Comment by jancborchardt** [comment]
Good catch – @NastuzziSamy do you want to look into that? :)

**Comment by MorrisJobke** [comment]
@NastuzziSamy 🏓

**Comment by NastuzziSamy** [comment]
I'm back ! :) 

PRs opened for today

**Comment by TobiVanHelsinki** [comment]
Hi, I have the same issue. Why was this Bug closed, was there a solution?

I have some Folders which I can delete and some not. Same UI as in the original Screenshot. If a Folder is not deletable, also all subfolders and files aren't. I event can't delete or move those files at my PC. They got resynced instantly. Same via WebDAV. I can rename them, but that doesn't change anything.

NC Version 19.0.5
Ubuntu 20.04
Unix user and rigths seems all correct.

This error affects most parts of my files. Have you any starting point for me?
