### ISSUE TITLE
Clicking the main content shows a menu with just share

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/files_rightclick#58]
This happens when clicking the white are of the files list (in grid view), share does nothing there, as there is no file that can be used. Maybe we should just show the new files menu there?

![image](https://user-images.githubusercontent.com/3404133/55223743-2cbbc100-520f-11e9-8960-6cff6fff5c1e.png)

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
> Maybe we should just show the new files menu there?

Yup, just like @NastuzziSamy suggested to show below the list in list view. :) :+1:
