### ISSUE TITLE
Make browser menu accessible

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/files_rightclick#59]
It should still be possible to open the native browser menu (e.g. when clicking with the Ctrl key pressed)

**Comment by jancborchardt** [comment]
It actually is possible as @NastuzziSamy showed me – by pressing Shift and clicking. :)

Added a simple note to the readme through https://github.com/nextcloud/files_rightclick/pull/60

**Comment by juliushaertl** [comment]
Doesn't work for me. None of the modifiers (Ctrl, Alt, Shift) work :confused:

**Comment by EV21** [comment]
It looks like "SHIFT + right click" is only working with Firefox. I am not shure if there is a feature for javascript to open the context-menu by element.  - I don't think so.

**Comment by NastuzziSamy** [comment]
I'm going to handle the Ctrl + Click action. By default, it is not handled, but I will add an option so we can force the handling

**Comment by jancborchardt** [comment]
Problem with Ctrl + Click is that for links in the browser it usually means "Open in new tab". So we should only do one thing, probably just making "Shift + Click" work? :)

**Comment by jancborchardt** [comment]
@NastuzziSamy did you see the comment before? :)

> Problem with Ctrl + Click is that for links in the browser it usually means "Open in new tab". So we should only do one thing, probably just making "Shift + Click" work? :)

**Comment by juliushaertl** [comment]
> Problem with Ctrl + Click is that for links in the browser it usually means "Open in new tab". So we should only do one thing, probably just making "Shift + Click" work? :) 

@jancborchardt it is about ctrl + right click, however the pull request just makes sure that whenever a modifier key is used we fallback to the browser default action, so the regular ctrl+left click is not affected.

**Comment by jancborchardt** [comment]
> it is about ctrl + right click

Oh jeez, nevermind me. :D I was thinking that I had to miss something …
