### ISSUE TITLE
Nc 16 - right-click menu not the same as ... menu

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/files_rightclick#61]
I'm running Nc 16 beta 2 and installed the extract app: https://apps.nextcloud.com/apps/extract

I don't know if app devs will have to do work/changes to support the app, I know it initially was meant for 17 but I thought I'd report at least this case :smile: 
![right-click-menu](https://user-images.githubusercontent.com/551757/55400865-4af72900-554f-11e9-8b48-79f4b2ac071d.png)

A few things broken, seemingly (screenshot edited to show both menu's of course):
* favorites
* an extra 'comment' item without icon
* missing "Extract here" item

**Comment by juliushaertl** [comment]
@NastuzziSamy As discussed at the hackweek, you should be able to get the file actions with this method: https://github.com/nextcloud/server/blob/6b2a212c698a49977b7b4216ce167661cb0f62af/apps/files/js/fileactions.js#L194

**Comment by NastuzziSamy** [comment]
@juliushaertl i got that when i try your API:
```js
OCA.Files.FileActions.prototype.get('httpd/unix-directory', 'dir', 31)
Object {  }

OCA.Files.FileActions.prototype.getActions('httpd/unix-directory', 'dir', 31)
Object {  }
```

**Comment by juliushaertl** [comment]
@NastuzziSamy You cannot call a function on the prototype, you need to call it on an actual object of the FileActions prototype. So it would be:

    OCA.Files.App.fileList.fileActions.get('httpd/unix-directory', 'dir', 31)

or for public pages

    OCA.Sharing.PublicApp.fileList.fileActions.get('httpd/unix-directory', 'dir', 31)

**Comment by NiTRoeSE** [comment]
I missing "delete" & "download" function in right click menu..still gone since NC 16.
Is there a way to fix it?

**Comment by ratermir** [comment]
I have the same issue in NC 16.0.1 and right click 0.13.0 - after upgrade from NC 15.0.5, items "Download" and "Delete" disapeared from the "right click" menu, so it differs from the "three button" menu.

**Comment by janis91** [comment]
I just want to mention, that this bug applies to other apps, that register file actions as well.

**Comment by ratermir** [comment]
One comment on this: the menu seems to be correct, when the file is "selected" by checking in the checkbox left of file name

**Comment by janis91** [comment]
@ratermir confirmed. Even for 3rd party apps.
