### ISSUE TITLE
duplicate delete in right click menu

### ISSUE THREAD

**Issue by w-e-w** [nextcloud/files_rightclick#65]
NC 15.0.7

When selecting the file or files using the checkbox,
then the right click menu has 2 deletes,
the first delete functions whiles the second dose nothing when use inside normal folder, the second one functions when the trash bin.

note: this behaiver when inside normal filder are not consistent.

![2019-04-14 21_41_52-000004](https://user-images.githubusercontent.com/40751091/56092977-4d1d9800-5efe-11e9-9adb-78bf3a22ee0d.png)

**Comment by NastuzziSamy** [comment]
This issue is fixed with the last versions: https://github.com/nextcloud/files_rightclick/pull/64

**Comment by DJCrashdummy** [comment]
at least with `files_rightclick` **0.15.1** there are still issues within the trash bin:
- [ ] i get an (untranslated) *"Share file"* entry, which makes no sense in both ways...
![Gelöschte Dateien - Nextcloud](https://user-images.githubusercontent.com/26110463/74916255-cced7c00-53c5-11ea-8a38-315de25675b9.png)
- [ ] after you have selected some files at *"All files"* and switch to the trash bin, suddenly the *"Select"* entry appears (although there is no file selected)... which is perfectly fine for me, but somehow inconsistent.
![Gelöschte Dateien - Nextcloud(2)](https://user-images.githubusercontent.com/26110463/74917437-c5c76d80-53c7-11ea-8d0d-84eb957de139.png)
- [ ] and if you have selected one file at the trash bin, it gets even worse and entries like *"Move or copy"* (without actually moving or copying) or *"Delete"* (additional to *"Delete permanently"*) appear:
![Gelöschte Dateien - Nextcloud(1)](https://user-images.githubusercontent.com/26110463/74918206-0a9fd400-53c9-11ea-9a85-abb5dff95118.png)
