### ISSUE TITLE
Right Click 0.13 nextcloud 16 Integrity Check fails

### ISSUE THREAD

**Issue by eduardotseoane** [nextcloud/files_rightclick#70]
sudo -u apache occ integrity:check-app files_rightclick
  - EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Signature data not found.

**Comment by createchange** [comment]
Relevant documentation for the dev: https://docs.nextcloud.com/server/16/admin_manual/issues/code_signing.html

I have the same issue.

**Comment by jonathanmmm** [comment]
Same:
 sudo -u www-data php occ integrity:check-app files_rightclick                                                        - EXTRA_FILE:
    - README.md:
      - expected: 
      - current: cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3


Disabling, removing and reinstalling and rescan made the error going away.

**Comment by jonathanmmm** [comment]
sudo -u www-data php occ integrity:check-app files_rightclick                                                        - EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Signature data not found.

(Is this right, no signature?)

But the error is gone in the webinterface

**Comment by jonathanmmm** [comment]
Ok, the Error is there again with:
The signature data Not found.

**Comment by ricain** [comment]
Same here.

**Comment by eduardotseoane** [comment]
It seem that that not occour after 16.0.1 update

**Comment by jonathanmmm** [comment]
I updated from 15.0.7 to 16.0.1 and the error came.

**Comment by uiharu-s** [comment]
The relevant thread on the forum:
https://help.nextcloud.com/t/nc-15-0-7-16-0-0-upgrade-file-integrity-check-failed/52611

A workaround to make the warning go away is to simply `rm /path/to/nextcloud/apps/files_rightclick/README.md`

**Comment by jonathanmmm** [comment]
I deleted the App and reinstalled, shouldn't it removed the package with the readme.md and download it without?

**Comment by Henk57** [comment]
Same problem with me after updating to Nextcloud 16.
Uninstall, reinstall did not solve the error.
Renaming README.md to README.md_fout did not solve the problem either.

`Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
                        )

                )

        )

)`

**Comment by quentinDupont** [comment]
Same problem here after updating to Nextcloud 16.

**Comment by AaronADev** [comment]
Same problem after the update from Nextcloud 16.0.1 to 16.0.2.

**Comment by Henk57** [comment]
Yes. Problem with 'offical app' remains.

**Comment by a1pilot** [comment]
Same here.

**Comment by mrs59** [comment]
yep - i have the same problem as well on Nextcloud 16.0.2

**Comment by Delor3an** [comment]
Hi Everybody,

Does a new release (0.14 ?) with a signature is in the loop ?

**Comment by NastuzziSamy** [comment]
Hi :)

I am adding this in a new release, I am just not just at home so I can make it. Wait max a week.

Thx for feedbacks, cheers

**Comment by unnilennium** [comment]
Back home ?@NastuzziSamy

**Comment by Githopp192** [comment]
same to me .. just did the Upgrade from 15.0.10 to 16.0.3 -->


Technical   information
--
=====================
The following list covers   which files have failed the integrity check. Please read
the previous linked   documentation to learn more about the errors and how to fix
them.
 
Results
=======
#NAME?
- EXTRA_FILE
- README.md
 
Raw output
==========
Array
(
[files_rightclick] => Array
(
[EXTRA_FILE] => Array
(
[README.md] => Array
(
[expected]   =>
[current] =>   cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
)
 
)

**Comment by tobiasKaminsky** [comment]
I had the same today with an upgrade to NC17 beta1:


```
[files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
                        )

                )

        )
```

**Comment by ricain** [comment]
This issue is 4 months old... I have uninstalled this APP!

Having a basic issue not resolved with a such high impact on security is not acceptable.

I apologize to the developer but this is not serious....

**Comment by NastuzziSamy** [comment]
@ricain I understand, no need to apologize, it is not serious from me ^^

Will be fixed in the next release
