### ISSUE TITLE
Right click menu no longer appears

### ISSUE THREAD

**Issue by Luticus** [nextcloud/files_rightclick#80]
Since updating to 0.15.0 the right click menu no longer appears.  I get the normal browser menu instead.  I'm in Firefox on Debian Buster, and I've tried refreshing with shift+click to bypass the cache.  I use Nexcloud 16.0.4 on Apache with php 7.3.  The browser doesn't seem to show any console errors when right clicking on a file.

**Comment by JoeatMJ** [comment]
Same issue here. NC 16.0.4 upgraded from NC15.0.11. Followed the same steps as @Luticus with same result. I also tried uninstalling the app from NC, restarting Apache, rebooting the server, and reinstalling. Same result. I have tried this on three different instances of NC16.0.4. This app is one of the best enhancements for NC. Subscribed. Please fix it soon!

**Comment by gschbro** [comment]
Confirmed, same here. NC 16.0.4 and Right Click 0.15.0.
Since upgraded from 0.13.0 to 0.15.0 the right click menu is disappeared.

**Comment by whisperdancer** [comment]
same issue since upgrade to 0.15.0. right click menu no longer appears. get standard windows menu. on ff, NC16.0.4.0

**Comment by prezeskk** [comment]
NC 16.0.4 & Right Click 0.15.0 not working

**Comment by IoanMihaila** [comment]
Updated today - NC 16.0.4 & Right Click 0.15.0 not working.
Right click context menu is no longer displayed. No errors in NC log but in browser Inspector

![image](https://user-images.githubusercontent.com/26002226/63415145-ef4a1100-c405-11e9-9cd2-7adeabb33b4b.png)

**Comment by supportA3WEB** [comment]
Hi.
Archive release 15.0 on apps.nextcloud.com is not up to date.

In file apps/files_rightclick/appinfo/app.php
add this line 
\OCP\Util::addScript('files_rightclick', 'script');
before line 18
\OCP\Util::addScript('files_rightclick', $include);

it's ok for me

**Comment by NastuzziSamy** [comment]
Thanks guys for the report, my bad during compilation, missed this one. 

Releasing 0.15.1 (thank you @supportA3WEB for pointing the problem)

**Comment by NastuzziSamy** [comment]
Let me know if the new release repares that :)

**Comment by JoeatMJ** [comment]
When should it be available on the NC app store?

-----Original Message-----

**Comment by Luticus** [comment]
Yes, I can confirm this works.  @JoeatMJ I got my download from the appstore so it should be there now.  @NastuzziSamy Thanks for fixing this so quickly, I love my right click menu! :)

**Comment by gschbro** [comment]
Confirmed, the right click menu ist back!
Thank you :-)

**Comment by JoeatMJ** [comment]
I just updated to 0.15.1 and it is working brilliantly. Excellent work, @NastuzziSamy ! Thank you for the quick fix!

**Comment by NastuzziSamy** [comment]
Let me know if the new release repares that :)
