### ISSUE TITLE
Right click not working after latest update

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/files_rightclick#83]
The latest right click update totally broke the app - it will throw a log error once installed/enabled and will not work at all.

System: nextcloud 15 / snap ; ubuntu 19

![Screenshot_1](https://user-images.githubusercontent.com/36133540/63611675-b6b06000-c5dc-11e9-85fb-1b077826cd7b.png)

**Comment by erictwo** [comment]
Having problems also. Nextcloud wants me to update but won't, it fails to update. Menu shows up when right click but does nothing when acted upon. This started about 3 days ago.


Error | PHP | copy(/nextcloud/apps/files_rightclick/files_rightclick/l10n/zh_TW.json):  failed to open stream: No such file or directory at  /nextcloud/lib/private/legacy/helper.php#149 |

**Comment by cx-jv** [comment]
Same problem with our installation (Right click 0.15.1, NC 15.0.10.0 on Snap, PHP version Version: 7.2.21). The problem occured after updating Right click to 0.15.1.
![Opera Momentaufnahme_2019-08-27_204808](https://user-images.githubusercontent.com/54598639/63799323-2fc8f380-c90c-11e9-8def-85073d62744a.png)

**Comment by snake2903** [comment]
NC 15.0.11.1
PHP 7.1.31
MariaDB 5.5.60
Right Click 0.15.1

Same problem here... Updated to new version an after that it wont work.
It's located in apps and Disabled. After Enabling, nothing happens, app stays disabled.
I tried to remove it and reinstall it,but didn't work.

![RightClick](https://user-images.githubusercontent.com/7978035/63828547-32a50200-c967-11e9-91c6-b52e75809669.png)

**Comment by hermann1514** [comment]
same by me. RightClick is disabled after enable. NC15.11

**Comment by kurjajuur666** [comment]
Same problem here. NC 15.0.7. Older versions have the same issue at least after I updated to the latest version and tried older ones (0.14.1, 0.15.0)

**Comment by ossrac** [comment]
Same problem with NC 15.0.11. The issue happened when I updated Right click last time to 0.15.1.
After Enabling, nothing happens, the app stays disabled.
I tried to reinstall it, but it didn't work.

**Comment by jameslao** [comment]
Same problem with NC 18.0.0 Alpha

**Comment by PeeBeerBeach** [comment]
Exactly the same problem on NC 15.0.12 and Right Click 0.15.1

Í freshly installed the app. After activating it, it deactivates itself instantly.
Error log shows the exact same as first post.
Reinstallation brings no joy.

**Comment by cdisabatino** [comment]
Same problem with NC 15.0.5 and Right click 0.15.1.

Error : EVENT_LOAD_ADDITIONAL_SCRIPTS_LOGGEDIN

**Comment by 3dsman** [comment]
same here!
Error: Undefined class constant 'EVENT_LOAD_ADDITIONAL_SCRIPTS_LOGGEDIN'
/var/www/nextcloud/lib/private/legacy/app.php - line 261: require_once()
/var/www/nextcloud/lib/private/legacy/app.php - line 154: OC_App::requireAppFile("files_rightclick")
/var/www/nextcloud/lib/private/legacy/app.php - line 127: OC_App::loadApp("files_rightclick")
/var/www/nextcloud/lib/base.php - line 972: OC_App::loadApps()
/var/www/nextcloud/index.php - line 42: OC::handleRequest()

**Comment by billgertz** [comment]
With NC 17.02 right click 0.15.1 does not work. The context menu appears but none of the actions work. Backing down to 0.13.0 does work although it requires a bit of hacking. 

1) Download the 0.13.0 version from repository [here](https://github.com/nextcloud/files_rightclick/releases/tag/v0.13.0).
2) On the NC server goto _/usr/local/lib/owncloud/apps_ directory and rename the _files__rightclick_ to _old.files__rightclick_
3) Untar and uncompress the the gzipped tar ball in _/usr/local/lib/owncloud/apps_"
`tar zxf files_rightclick.tar.gz`
4) Set the ownership to the correct owner and group, in my case _www-data_:
`chown -R www-data:www-data files_rightclick`
5) Change to the _files_rightclick/appinfo_ directory:
`cd files_rightclick/appinfo`
6) Make a backup copy of the _info.xml_ file:
`cp info.xml info.xml.orig`
7) Edit the _info.xml_ file to change the xml _version_ tag from _0.13.0_ to _0.15.1_:
From:
```
<info xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://apps.nextcloud.com/schema/apps/info.xsd">
    <id>files_rightclick</id>
    <name>Right click</name>
    <summary>Right click menu for Nextcloud</summary>
    <description><![CDATA[This app allows users and developers to have a right click menu. Simply use the RightClick object to quickly create context menus. The Files app already shows the actions menu when right clicking on files and folders.]]></description>
    <version>0.15.1</version>
    <licence>AGPL</licence>
.
.
.
```
To:
```
<info xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://apps.nextcloud.com/schema/apps/info.xsd">
    <id>files_rightclick</id>
    <name>Right click</name>
    <summary>Right click menu for Nextcloud</summary>
    <description><![CDATA[This app allows users and developers to have a right click menu. Simply use the RightClick object to quickly create context menus. The Files app already shows the actions menu when right clicking on files and folders.]]></description>
    <version>0.13.0</version>
    <licence>AGPL</licence>
.
.
.
```
This is probably not kosher and an ugly hack that will break things (TM Pending). But it get you around the App Update message that will come up when you try to login. YMMV.
