### ISSUE TITLE
Files not passed integrity check after update to 17.0.1

### ISSUE THREAD

**Issue by zombielinux** [nextcloud/files_rightclick#89]
User -> Settings -> Overview shows an integrity check error. 

Reproducible: Yes, follow instructions in README.md for installation. 

```Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

**Comment by MarcJose** [comment]
Same here but different file:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => 008148d723136644c2542312557ed5b9db1af5de6797a221d221012ae0ad367b2daca4774bcaba8936ec8394093b83c3e3f2d8e7c52e5f5882e28579dffe99e2
                        )

                )

        )

)
```

**Comment by siduxdevil** [comment]
Same here.`Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3`

**Comment by tiiiecherle** [comment]
> Same here but different file:
> 
> ```
> Technical information
> =====================
> The following list covers which files have failed the integrity check. Please read
> the previous linked documentation to learn more about the errors and how to fix
> them.
> 
> Results
> =======
> - files_rightclick
> 	- EXTRA_FILE
> 		- README.md
> 
> Raw output
> ==========
> Array
> (
>     [files_rightclick] => Array
>         (
>             [EXTRA_FILE] => Array
>                 (
>                     [README.md] => Array
>                         (
>                             [expected] => 
>                             [current] => 008148d723136644c2542312557ed5b9db1af5de6797a221d221012ae0ad367b2daca4774bcaba8936ec8394093b83c3e3f2d8e7c52e5f5882e28579dffe99e2
>                         )
> 
>                 )
> 
>         )
> 
> )
> ```

same for me...
