### ISSUE TITLE
No translation - Share ...

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/files_rightclick#91]
There is no translation for:

- Share file
- Share folder

for deleted files (trash).

![obraz](https://user-images.githubusercontent.com/47037905/72534494-346c5500-3877-11ea-9ed2-1dd41b04243d.png)

It's the code line:
https://github.com/nextcloud/files_rightclick/blob/48436318524a754b61273b8648cab34b4ca4d812/js/files.js#L85

There is a translation into Transifex for the Polish language.
In my opinion, this option should be available in the "All files" menu, not in "Deleted files".

App:
Nextcloud 17.0.2
Right click 0.15.1

**Comment by Valdnet** [comment]
@NastuzziSamy, @rullzer, @nickvergessen In the "files_rightclick" module, the following errors occur in addition to the one indicated above:

1. In "Files", after selecting the file and clicking the right mouse button on the menu should not find the option "Delete permanently" and after clicking on this option nothing happens. This function is superfluous, because it should only be in "Trash".

![obraz](https://user-images.githubusercontent.com/47037905/79067986-c263aa80-7cc3-11ea-88fa-b81ae1c881c4.png)

2. In "Trash" after selecting the file and right-clicking on the menu, the option "Trash" should not appear. And again, as in the previous case, nothing happens after clicking.

![obraz](https://user-images.githubusercontent.com/47037905/79068104-8c72f600-7cc4-11ea-815d-84f20409ea04.png)

In both cases, the items listed are superfluous.

Nextcloud 18.0.3 and 19.0.0 beta2
Right click 0.16.0

**Comment by nickvergessen** [comment]
Yeah, the app should not recreate the actions from the ... menu but inherit them from there instead.

**Comment by Valdnet** [comment]
In the NC version 22.0.0, one of the errors still occurs:

![obraz](https://user-images.githubusercontent.com/47037905/72534494-346c5500-3877-11ea-9ed2-1dd41b04243d.png)
